name: "cd-frontend"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Find Process and Send SIGINT
        run: |
            PID=$(ps aux | grep 'npm start' | grep -v grep | awk '{print $2}')
            if [ -n "$PID" ]; then
              kill -2 $PID
            fi

      - name: Install dependences
        run: npm install

      - name: Build next
        run: npm run build

      - name: Run aplication
        run: nohup npm start > output.log 2>&1 &
